/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as managableSol from "./Managable.sol";
export type { managableSol };
import type * as onftSol from "./ONFT.sol";
export type { onftSol };
import type * as ousdSol from "./OUSD.sol";
export type { ousdSol };
export type { ERC20i } from "./ERC20i";
export type { FundStorage } from "./FundStorage";
export type { Lock } from "./Lock";
export type { PropertyManager } from "./PropertyManager";
export type { PropertyStorage } from "./PropertyStorage";
export type { UserManager } from "./UserManager";
