/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type PropertyStruct = {
  id: PromiseOrValue<BigNumberish>;
  name: PromiseOrValue<string>;
  owner: PromiseOrValue<string>;
  price: PromiseOrValue<BigNumberish>;
  funds: PromiseOrValue<BigNumberish>;
  images: PromiseOrValue<string>[];
  fundStorage: PromiseOrValue<string>;
  status: PromiseOrValue<BigNumberish>;
  verified: PromiseOrValue<boolean>;
  location: PromiseOrValue<string>;
};

export type PropertyStructOutput = [
  BigNumber,
  string,
  string,
  BigNumber,
  BigNumber,
  string[],
  string,
  number,
  boolean,
  string
] & {
  id: BigNumber;
  name: string;
  owner: string;
  price: BigNumber;
  funds: BigNumber;
  images: string[];
  fundStorage: string;
  status: number;
  verified: boolean;
  location: string;
};

export interface PropertyStorageInterface extends utils.Interface {
  functions: {
    "createNewProperty(string,uint256,string[],string,address,address)": FunctionFragment;
    "flagProperty(uint256)": FunctionFragment;
    "getProperties(uint256,uint256)": FunctionFragment;
    "getProperty(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeProperty(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setProperty(uint256,(uint256,string,address,uint256,uint256,string[],address,uint8,bool,string))": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "verify(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createNewProperty"
      | "flagProperty"
      | "getProperties"
      | "getProperty"
      | "owner"
      | "removeProperty"
      | "renounceOwnership"
      | "setProperty"
      | "transferOwnership"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createNewProperty",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flagProperty",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProperties",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProperty",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeProperty",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProperty",
    values: [PromiseOrValue<BigNumberish>, PropertyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createNewProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flagProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PropertyAdded(uint256)": EventFragment;
    "PropertyRemoved(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PropertyAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PropertyRemoved"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PropertyAddedEventObject {
  _id: BigNumber;
}
export type PropertyAddedEvent = TypedEvent<
  [BigNumber],
  PropertyAddedEventObject
>;

export type PropertyAddedEventFilter = TypedEventFilter<PropertyAddedEvent>;

export interface PropertyRemovedEventObject {
  _id: BigNumber;
}
export type PropertyRemovedEvent = TypedEvent<
  [BigNumber],
  PropertyRemovedEventObject
>;

export type PropertyRemovedEventFilter = TypedEventFilter<PropertyRemovedEvent>;

export interface PropertyStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PropertyStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createNewProperty(
      _name: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _images: PromiseOrValue<string>[],
      _location: PromiseOrValue<string>,
      _owner: PromiseOrValue<string>,
      _fundStorage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    flagProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getProperties(
      _offset: PromiseOrValue<BigNumberish>,
      _limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [PropertyStructOutput[], BigNumber, BigNumber] & {
        props: PropertyStructOutput[];
        nextOffset: BigNumber;
        total: BigNumber;
      }
    >;

    getProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[PropertyStructOutput]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProperty(
      _property: PromiseOrValue<BigNumberish>,
      value: PropertyStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verify(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createNewProperty(
    _name: PromiseOrValue<string>,
    _price: PromiseOrValue<BigNumberish>,
    _images: PromiseOrValue<string>[],
    _location: PromiseOrValue<string>,
    _owner: PromiseOrValue<string>,
    _fundStorage: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  flagProperty(
    _property: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getProperties(
    _offset: PromiseOrValue<BigNumberish>,
    _limit: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [PropertyStructOutput[], BigNumber, BigNumber] & {
      props: PropertyStructOutput[];
      nextOffset: BigNumber;
      total: BigNumber;
    }
  >;

  getProperty(
    _property: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<PropertyStructOutput>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeProperty(
    _property: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProperty(
    _property: PromiseOrValue<BigNumberish>,
    value: PropertyStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verify(
    _property: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createNewProperty(
      _name: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _images: PromiseOrValue<string>[],
      _location: PromiseOrValue<string>,
      _owner: PromiseOrValue<string>,
      _fundStorage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PropertyStructOutput>;

    flagProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getProperties(
      _offset: PromiseOrValue<BigNumberish>,
      _limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [PropertyStructOutput[], BigNumber, BigNumber] & {
        props: PropertyStructOutput[];
        nextOffset: BigNumber;
        total: BigNumber;
      }
    >;

    getProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PropertyStructOutput>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setProperty(
      _property: PromiseOrValue<BigNumberish>,
      value: PropertyStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    verify(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PropertyAdded(uint256)"(_id?: null): PropertyAddedEventFilter;
    PropertyAdded(_id?: null): PropertyAddedEventFilter;

    "PropertyRemoved(uint256)"(_id?: null): PropertyRemovedEventFilter;
    PropertyRemoved(_id?: null): PropertyRemovedEventFilter;
  };

  estimateGas: {
    createNewProperty(
      _name: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _images: PromiseOrValue<string>[],
      _location: PromiseOrValue<string>,
      _owner: PromiseOrValue<string>,
      _fundStorage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    flagProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getProperties(
      _offset: PromiseOrValue<BigNumberish>,
      _limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProperty(
      _property: PromiseOrValue<BigNumberish>,
      value: PropertyStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verify(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createNewProperty(
      _name: PromiseOrValue<string>,
      _price: PromiseOrValue<BigNumberish>,
      _images: PromiseOrValue<string>[],
      _location: PromiseOrValue<string>,
      _owner: PromiseOrValue<string>,
      _fundStorage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    flagProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getProperties(
      _offset: PromiseOrValue<BigNumberish>,
      _limit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeProperty(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProperty(
      _property: PromiseOrValue<BigNumberish>,
      value: PropertyStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verify(
      _property: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
